---
- hosts: all
  connection: local

  vars: 
    
    github_version: "v4.18.2"
    github_dic: {
        "github_repository_name": "test",
         "github_branch_default": "main",
        "github_branch_protection": "test_id",
        "github_name": 'test1',
        "github_description": 'A description of the repository',
                  }

  roles:
    - { role: "sometest"}       
