---
- hosts: localhost
  connection: local

  vars:
    github_version: "v4.18.2"
    github_list:
      - github_repository_name: "first_OPs_repo"
        github_branch_default: "main1"
        github_branch_protection: "first_OPs_repo_id"
        github_name: "first_OPs_repository"
        github_description: "A description of the repository"
      - github_repository_name: "second_OPs_repo" 
        github_branch_default: "main2"
        github_branch_protection: "second_OPs_repo_id"
        github_name: "second_OPs_repository"
        github_description: "second description of the repository"

    

  roles:
    - { role: "sometest" }       
