---     
- name: Template a file to main.tf
  ansible.builtin.template:
    src: "main.tf.j2"
    dest: "/mnt/c/Users/admin/iac/iac-github/main.tf"
    mode: '0644'
    owner: "proadmin"
    group: "proadmin"
    
- include_tasks: resources.yaml
  loop:
     "{{ github_list }}" 
  loop_control:
    loop_var: outer_item
