- name: Template a file to resources.tf
  ansible.builtin.template:
    src: "resources.tf.j2"
    dest: "/mnt/c/Users/admin/iac/iac-github/generated/resources_{{github_repository_name}}.tf"
    mode: '0644'
    owner: "proadmin"
    group: "proadmin"
