name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ansible_playbook_job:
    runs-on: ubuntu-latest
    name: Execute  Playbook
    steps:
      - uses: actions/checkout@v1
      - name: Run Ansible Playbook
      - uses: ./iac-github/playbook.yaml
#         run: ansible-playbook ./iac-github/playbook.yaml
