name: Run Ansible Playbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  ansible_playbook_job:
    runs-on: ubuntu-latest
    name: Execute  Playbook
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Open Ops repository Directory
        working-directory: ./iac-github
        run: |
          ls -la
      - name: Run Ansible Playbook
        working-directory: ./iac-github
        run: ansible-playbook playbook.yaml
#       - name: List files in runner.temp
#         working-directory: ${{ runner.temp }}
#         run: find ./ -type f

      - name: 'Terraform'
        working-directory: /tmp/generated_tf
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
