name: Test Ansible

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ansible_playbook_job:
    runs-on: ubuntu-latest
#     name: Create target directory
#       - path: ./Ops-repository/iac-github state=directory mode=0755 
    name: Execute  Playbook
    steps:
      - uses: actions/checkout@v1
      - name: Run Ansible Playbook
        run: ansible-playbook ./home/runner/iac-github/playbook.yaml
        
