name: Run Ansible Playbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  ansible_playbook_job:
    runs-on: ubuntu-latest
    name: Execute  Playbook
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Open Ops repository Directory
        working-directory: ./iac-github
        run: |
          ls -la

      - name: Run Ansible Playbook
        working-directory: ./iac-github
        run: ansible-playbook playbook.yaml

#       - name: List files in runner.temp
#         run: echo ${{ runner.temp }}

#       - name: "move generated files to another address"
#         run: mkdir -p /github/workspace/generate_tf && mv /tmp/generate_tf/* /github/workspace/generate_tf

      - name: "list files"
        run: ls -ltrh /tmp/generated_tf


      - uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check



      - name: init terraform
        working-directory: /tmp/generated_tf
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: terraform plan
        working-directory: /tmp/generated_tf
        run: terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
          
      - name: Terraform Apply
        working-directory: /tmp/generated_tf
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve


          
#       - name: terraform apply
#         working-directory: /tmp/generated_tf
#         run: terraform apply
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

#       - name: 'Terraform'
#         uses: hashicorp/terraform-github-actions@master
#         with:
#           tf_actions_version: 0.12.18
#           tf_actions_subcommand: 'init'
#           tf_actions_working_dir: 'generate_tf'
#           tf_actions_comment: true

        
