name: Test Ansible

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ansible_playbook_job:
    runs-on: ubuntu-latest
    name: Execute  Playbook
    steps:
      - uses: actions/checkout@v1
      - name: Create target directory
        with:
          path: ~/iac-github
      - name: Open Ops repository Directory
        working-directory: ./iac-github
        run: |
          ls -la
      - name: Run Ansible Playbook
        run: ansible-playbook ./iac-github/playbook.yaml
        
