name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ansible_playbook_job:
    runs-on: ubuntu-latest
    name: Execute  Playbook
    steps:
      - uses: actions/checkout@v1
      - name: Execute Playbook Action Step
        id: Execution
        uses: samisgh/Ops-repository@master
        with:
          playbookName: "playbook.yml"
