name: Ansible Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Ansible Playbook
      with: 
        playbook: playbook.yml
        inventory: localhost
    - name: Run ansible
      run: ansible-playbook -i localhost, -c local playbook.yaml 
      working-directory: ./Ops-repository



