name: Ansible Lint 

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  run-playbooks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Ansible Playbook
      run: ansible-playbook -i localhost, -c local playbook.yaml 

