name: Run Ansible-Trraform playbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  ansible_playbook_job:
    runs-on: ubuntu-latest
    name: Execute  Playbook
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Open Ops repository Directory
        working-directory: ./iac-github
        run: |
          ls -la

      - name: Run Ansible Playbook
        working-directory: ./iac-github
        run: ansible-playbook playbook.yaml


      - name: "list files"
        run: ls -ltrh /tmp/generated_tf

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check



      - name: init Terraform
        working-directory: /tmp/generated_tf
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color


          
      - name: Terraform plan
        working-directory: /tmp/generated_tf
        run: terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
          
      - name: Terraform Apply
        working-directory: /tmp/generated_tf
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
